export const socketEvents = {
  LOAD_LOBBY_TIMER: 'loadLobbyTimer',
  TABLES_LIST: 'tablesListLobby',
  START_TABLE: 'startTable',
  LOAD_RESULTS: 'loadResults',
  SHOW_RESULTS: 'showResults',
  LOAD_ROOM_TIMER: 'loadRoomTimer',
  SEND_DURATION: 'sendDuration',
  LOAD_DEALER_TIMER: 'loadDealerTimer',
  RESET_TABLE: 'resetTable',
  SEND_DURATION_USER: 'sendDurationToUser',
  DURATION_FROM_DEALER_TO_LOBBY: 'durationFromDealerToLobby',
  DURATION_FROM_DEALER_TO_ROOM: 'durationFromDealerToRoom',
  CHANGE_STATUS: 'changeStatus',
  PLAY_SOUND: 'playSound',
  JOIN_AS_DEALER: 'joinTableAsDealer',
  JOIN_AS_PLAYER: 'joinTableAsPlayer',
  LEAVE_AS_PLAYER: 'leaveTableAsPlayer',
  RECEIVE_CARDS: 'receiveCards',
  START_TIMER_LOBBY: 'startTimerLobby',
  START_TIMER_ROOM: 'startTimerRoom',
  UPDATE_TABLE_LOBBY: 'updateTableLobby',
  UPDATE_TABLE_ROOM: 'updateTableRoom',
  SHOW_RESULTS_ROOM: 'showResultsRoom',
};
