export const SFX = {
  click: '/sounds/sfx/click.mp3',
  chipDrop: '/sounds/sfx/chip-drop.mp3',
  startBetting: {
    en: '/sounds/sfx/start-betting.mp3',
    kr: '/sounds/sfx/start-betting-kr.mp3',
    jp: '/sounds/sfx/start-betting-jp.mp3',
    cn: '/sounds/sfx/start-betting-cn.mp3',
    vn: '/sounds/sfx/start-betting-vn.mp3',
  },
  stopBetting: {
    en: '/sounds/sfx/stop-betting.mp3',
    kr: '/sounds/sfx/stop-betting-kr.mp3',
    jp: '/sounds/sfx/stop-betting-jp.mp3',
    cn: '/sounds/sfx/stop-betting-cn.mp3',
    vn: '/sounds/sfx/stop-betting-vn.mp3',
  },
  bankerWins: {
    en: '/sounds/sfx/banker-wins.mp3',
    kr: '/sounds/sfx/banker-wins-kr.mp3',
    jp: '/sounds/sfx/banker-wins-jp.mp3',
    cn: '/sounds/sfx/banker-wins-cn.mp3',
    vn: '/sounds/sfx/banker-wins-vn.mp3',
  },
  playerWins: {
    en: '/sounds/sfx/player-wins.mp3',
    kr: '/sounds/sfx/player-wins-kr.mp3',
    jp: '/sounds/sfx/player-wins-jp.mp3',
    cn: '/sounds/sfx/player-wins-cn.mp3',
    vn: '/sounds/sfx/player-wins-vn.mp3',
  },
  tieWins: {
    en: '/sounds/sfx/tie-wins.mp3',
    kr: '/sounds/sfx/tie-wins-kr.mp3',
    jp: '/sounds/sfx/tie-wins-jp.mp3',
    cn: '/sounds/sfx/tie-wins-cn.mp3',
    vn: '/sounds/sfx/tie-wins-vn.mp3',
  },
  //niu niu
  banker: '/sounds/sfx/banker.mp3',
  player1: '/sounds/sfx/player-1.mp3',
  player2: '/sounds/sfx/player-2.mp3',
  player3: '/sounds/sfx/player-3.mp3',
  noBull: '/sounds/sfx/no-bull.mp3',
  bull1: '/sounds/sfx/bull-1.mp3',
  bull2: '/sounds/sfx/bull-2.mp3',
  bull3: '/sounds/sfx/bull-3.mp3',
  bull4: '/sounds/sfx/bull-4.mp3',
  bull5: '/sounds/sfx/bull-5.mp3',
  bull6: '/sounds/sfx/bull-6.mp3',
  bull7: '/sounds/sfx/bull-7.mp3',
  bull8: '/sounds/sfx/bull-8.mp3',
  bull9: '/sounds/sfx/bull-9.mp3',
  niu1: '/sounds/sfx/niu-1.mp3',
  niu2: '/sounds/sfx/niu-2.mp3',
  niu3: '/sounds/sfx/niu-3.mp3',
  niu4: '/sounds/sfx/niu-4.mp3',
  niu5: '/sounds/sfx/niu-5.mp3',
  niu6: '/sounds/sfx/niu-6.mp3',
  niu7: '/sounds/sfx/niu-7.mp3',
  niu8: '/sounds/sfx/niu-8.mp3',
  niu9: '/sounds/sfx/niu-9.mp3',
  niuNiu: '/sounds/sfx/niu-niu.mp3',
  highCard: '/sounds/sfx/high-card.mp3',
};

export const MUSIC = {
  bgm: '/sounds/music/bgm.mp3',
};
